[package]
name = "eel_wasm"
version = "0.1.0"
authors = ["Jordan Eldredge <jordan@jordaneldredge.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
parity-wasm = "0.42.2"
structopt = "0.3.21"
indexmap = "1.6.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }


[dev-dependencies]
wasmi = "0.8.0"
wabt = "0.9.0"
wasm-bindgen-test = "0.3.13"
wasmprinter = "0.2.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

